# ===================================================
# bot/config.py
# Bot Configuration — Environment Variables & Constants
# TopKap Telegram Bot — KAYISOFT Integration
# ===================================================

import os
import logging
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

logger = logging.getLogger(__name__)

# ── Telegram Bot ──────────────────────────────────────────────────────────────
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN") or os.getenv("BOT_TOKEN", "")

# ── KAYISOFT API ──────────────────────────────────────────────────────────────
# Base URL for the KAYISOFT Wholesale Backend (Staging)
KAYISOFT_API_URL = os.getenv("KAYISOFT_API_URL", "https://api-wholesale.dev.kayisoft.net")

# Fixed Bearer Token used in Authorization header for ALL KAYISOFT endpoints.
# This is TELEGRAM_BOT_API_ENDPOINT_KEY — provided by KAYISOFT.
# IMPORTANT: This is NOT the Deep Link token. The Deep Link token is only used
# in the POST /api/seller/telegram-bot/connect request body as "token".
# يقرأ من KAYISOFT_API_TOKEN أولاً، ثم TELEGRAM_BOT_API_ENDPOINT_KEY كـ fallback للتوافق مع Railway
KAYISOFT_API_TOKEN = os.getenv("KAYISOFT_API_TOKEN") or os.getenv("TELEGRAM_BOT_API_ENDPOINT_KEY", "")

# Deep Link base URL — generated by the mobile app to link seller account to bot
TELEGRAM_BOT_CONNECT_BASE_URL = os.getenv(
    "TELEGRAM_BOT_CONNECT_BASE_URL",
    "https://t.me/TopKapTR_bot?start="
)

# ── AI Services ───────────────────────────────────────────────────────────────
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")

# ── Admin ─────────────────────────────────────────────────────────────────────
# No administrator identifier is embedded in source code.  DevOps must provide
# this value through the deployment environment when administrative alerts are used.
_admin_id_raw = os.getenv("ADMIN_TELEGRAM_ID", "").strip()
try:
    ADMIN_TELEGRAM_ID = int(_admin_id_raw) if _admin_id_raw else None
except ValueError as exc:
    raise ValueError("ADMIN_TELEGRAM_ID must be a numeric Telegram user ID.") from exc

# ── Language Defaults ─────────────────────────────────────────────────────────
DEFAULT_LANGUAGE    = "tr"                  # Turkish — default for Turkish suppliers
SUPPORTED_LANGUAGES = ["tr", "ar", "en"]   # Turkish / Arabic / English

# ── Validation ────────────────────────────────────────────────────────────────
if not BOT_TOKEN:
    raise ValueError(
        "❌ TELEGRAM_BOT_TOKEN is missing.\n"
        "Please copy .env.example to .env and set the correct token."
    )

if not KAYISOFT_API_TOKEN:
    raise ValueError(
        "KAYISOFT API credential is missing. Set KAYISOFT_API_TOKEN or "
        "TELEGRAM_BOT_API_ENDPOINT_KEY in the deployment environment."
    )
