# ===================================================
# bot/config.py
# Bot Configuration — Environment Variables & Constants
# TopKap Telegram Bot — KAYISOFT Integration
# ===================================================

import os
import logging
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

logger = logging.getLogger(__name__)

# ── Telegram Bot ──────────────────────────────────────────────────────────────
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

# ── KAYISOFT API ──────────────────────────────────────────────────────────────
# Base URL for the KAYISOFT Wholesale Backend (Staging)
KAYISOFT_API_URL = os.getenv("KAYISOFT_API_URL", "https://api-wholesale.dev.kayisoft.net")

# Fixed Bearer Token used in Authorization header for ALL KAYISOFT endpoints.
# This is TELEGRAM_BOT_API_ENDPOINT_KEY — provided by KAYISOFT.
# IMPORTANT: This is NOT the Deep Link token. The Deep Link token is only used
# in the POST /api/seller/telegram-bot/connect request body as "token".
KAYISOFT_API_TOKEN = os.getenv("TELEGRAM_BOT_API_ENDPOINT_KEY", "")

# Deep Link base URL — generated by the mobile app to link seller account to bot
TELEGRAM_BOT_CONNECT_BASE_URL = os.getenv(
    "TELEGRAM_BOT_CONNECT_BASE_URL",
    "https://t.me/TopKapTR_bot?start="
)

# ── AI Services ───────────────────────────────────────────────────────────────
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")

# ── Admin ─────────────────────────────────────────────────────────────────────
ADMIN_TELEGRAM_ID = int(os.getenv("ADMIN_TELEGRAM_ID", "5733520948"))

# ── Language Defaults ─────────────────────────────────────────────────────────
DEFAULT_LANGUAGE    = "tr"                  # Turkish — default for Turkish suppliers
SUPPORTED_LANGUAGES = ["tr", "ar", "en"]   # Turkish / Arabic / English

# ── Validation ────────────────────────────────────────────────────────────────
if not BOT_TOKEN:
    raise ValueError(
        "❌ TELEGRAM_BOT_TOKEN is missing.\n"
        "Please copy .env.example to .env and set the correct token."
    )

if not KAYISOFT_API_TOKEN:
    logger.warning(
        "⚠️  TELEGRAM_BOT_API_ENDPOINT_KEY is not set. "
        "All KAYISOFT API calls will fail."
    )
