"""
bot/services/kayisoft_api.py
============================
KAYISOFT Wholesale API Client — TopKap Telegram Bot

All endpoints MUST include these headers (per KAYISOFT documentation):
    Telegram-User-Id : <telegram_user_id>
    Authorization    : Bearer <token>
    Platform         : telegram
    Accept-Language  : <language_code>  (tr | ar | en)
"""
import os
import hashlib
import logging
import aiohttp
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

KAYISOFT_API_URL   = os.getenv("KAYISOFT_API_URL",   "https://api-wholesale.dev.kayisoft.net")
KAYISOFT_API_TOKEN = os.getenv("KAYISOFT_API_TOKEN",  "")


class KayisoftAPI:
    """
    Async HTTP client for the KAYISOFT Wholesale Backend.

    Usage:
        api = KayisoftAPI(telegram_user_id="123456789", language="tr", token="<bearer>")
        categories = await api.get_categories()
    """

    def __init__(
        self,
        telegram_user_id: str,
        language: str = "tr",
        token: Optional[str] = None,
    ):
        self.telegram_user_id = str(telegram_user_id)
        self.language         = language
        self.token            = token or KAYISOFT_API_TOKEN
        self.base_url         = KAYISOFT_API_URL.rstrip("/")

    # ── Headers ──────────────────────────────────────────────────────────────

    def _headers(self) -> dict:
        """
        Build the mandatory headers required by every KAYISOFT endpoint.
        """
        return {
            "Telegram-User-Id": self.telegram_user_id,
            "Authorization":    f"Bearer {self.token}",
            "Platform":         "telegram",
            "Accept-Language":  self.language,
            "Content-Type":     "application/json",
            "Accept":           "application/json",
        }

    # ── Low-level helpers ─────────────────────────────────────────────────────

    async def _get(self, endpoint: str, params: dict = None):
        url = f"{self.base_url}/{endpoint.lstrip('/')}"
        async with aiohttp.ClientSession() as session:
            try:
                async with session.get(
                    url,
                    headers=self._headers(),
                    params=params,
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as resp:
                    data = await resp.json()
                    if resp.status >= 400:
                        logger.error("GET %s → %s: %s", endpoint, resp.status, data)
                        return None
                    return data
            except Exception as exc:
                logger.error("GET %s error: %s", endpoint, exc)
                return None

    async def _post(self, endpoint: str, body: dict = None):
        url = f"{self.base_url}/{endpoint.lstrip('/')}"
        async with aiohttp.ClientSession() as session:
            try:
                async with session.post(
                    url,
                    headers=self._headers(),
                    json=body or {},
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as resp:
                    data = await resp.json()
                    if resp.status >= 400:
                        logger.error("POST %s → %s: %s", endpoint, resp.status, data)
                        return None
                    return data
            except Exception as exc:
                logger.error("POST %s error: %s", endpoint, exc)
                return None

    # ── 1. Connect seller account ─────────────────────────────────────────────

    async def connect_account(
        self,
        deep_link_token: str,
        telegram_user_name: Optional[str] = None,
    ) -> Optional[dict]:
        """
        POST api/seller/telegram-bot/connect

        Called when the seller opens the deep link generated by the TopKap app.
        `deep_link_token` is the token embedded in the deep link URL — NOT the API token.

        Request body:
            token               : str   — from deep link
            telegram_user_id    : str
            telegram_user_name  : str   (optional)
        """
        body: dict = {
            "token":            deep_link_token,
            "telegram_user_id": self.telegram_user_id,
        }
        if telegram_user_name:
            body["telegram_user_name"] = telegram_user_name
        return await self._post("api/seller/telegram-bot/connect", body)

    # ── 2. Register channel ───────────────────────────────────────────────────

    async def create_channel(
        self,
        channel_id: str,
        channel_name: str,
    ) -> Optional[dict]:
        """
        POST api/seller/telegram-bot/create-channel

        Called after the bot is added as admin to the seller's Telegram channel.
        Registers the channel in the KAYISOFT backend.

        Request body:
            channel_id          : str
            telegram_user_id    : str
            channel_name        : str
        """
        body = {
            "channel_id":       str(channel_id),
            "telegram_user_id": self.telegram_user_id,
            "channel_name":     channel_name,
        }
        return await self._post("api/seller/telegram-bot/create-channel", body)

    # ── 3. Get categories ─────────────────────────────────────────────────────

    async def get_categories(self, parent_id: str = "") -> Optional[list]:
        """
        GET api/seller/categories?parent=<id>

        Pass parent_id="" (empty string) for root-level categories.
        Pass parent_id=<uuid> to get subcategories of a root category.

        Response: list of category objects
            id, name, selected_image, unselected_image, parent,
            ui_order, visible, home_image, is_visible_for_browsing,
            is_visible_for_creating, minimum_required_images,
            maximum_images, maximum_videos
        """
        return await self._get("api/seller/categories", params={"parent": parent_id})

    # ── 4. Get attributes for a leaf category ────────────────────────────────

    async def get_attributes(self, category_id: str) -> Optional[list]:
        """
        GET api/seller/categories/{id}/attributes

        Returns all attributes (with their options) for the selected leaf category.
        Used to dynamically build the product form shown to the seller.

        Response: list of attribute objects
            id, parent, associated, key, ui_type, ui_filter_type, name, description,
            is_variant_selector, variant_meta, ui_order, required,
            default_value, default_option_id, is_primary_variant_attribute, options[]
        """
        return await self._get(f"api/seller/categories/{category_id}/attributes")

    # ── 5. Get signed URLs for media upload ──────────────────────────────────

    @staticmethod
    def generate_filename(file_bytes: bytes) -> str:
        """
        Generate a valid filename for KAYISOFT media upload.
        Format: <ISO-8601 timestamp>-<SHA-256 hash>
        Example: 2026-05-14T10:00:00.000Z-136a82a872029fda...
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
        sha256    = hashlib.sha256(file_bytes).hexdigest()
        return f"{timestamp}-{sha256}"

    async def get_signed_urls(
        self,
        file_names: list[str],
        category_id: str,
    ) -> Optional[list]:
        """
        POST api/extensions/signed-urls

        Get pre-signed S3 upload URLs for product media files.
        file_names must follow format: <ISO-8601 timestamp>-<SHA-256 hash>

        Response: list of {fileName, url}
        """
        body = {
            "operation":   "put_product_variant_media",
            "file_names":  file_names,
            "category_id": category_id,
        }
        return await self._post("api/extensions/signed-urls", body)

    async def upload_media_to_s3(self, signed_url: str, file_bytes: bytes, content_type: str = "image/jpeg") -> bool:
        """
        Upload a media file directly to S3 using the signed URL.
        Returns True on success, False on failure.
        """
        async with aiohttp.ClientSession() as session:
            try:
                async with session.put(
                    signed_url,
                    data=file_bytes,
                    headers={"Content-Type": content_type},
                    timeout=aiohttp.ClientTimeout(total=60),
                ) as resp:
                    if resp.status in (200, 204):
                        return True
                    logger.error("S3 upload failed: %s", resp.status)
                    return False
            except Exception as exc:
                logger.error("S3 upload error: %s", exc)
                return False

    # ── 6. Create product ─────────────────────────────────────────────────────

    async def create_product(self, product_data: dict) -> Optional[dict]:
        """
        POST api/seller/products

        Full product payload including:
            name, product_no, category_id, shared_attributes,
            variants[] (each with: stock_id, stock_count, visibility_status,
            titles[], descriptions[], prices[], images[], videos[],
            selector_attributes[], dimensions)

        Response: the created product object
        """
        return await self._post("api/seller/products", product_data)
